# Generated by Django 2.1.1 on 2019-03-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190314_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateField(),
        ),
    ]
